	_uniform = ["U_I_pilotCoveralls","U_O_PilotCoveralls"];
	_vest = [];
	_backpack = ["B_FieldPack_cbr"];
	_headgear = ["H_PilotHelmetHeli_O","H_PilotHelmetFighter_O"];
	_items = _items + ["Medikit","O_UavTerminal"]; 
	_primaryWeapon = [];
	_handgunWeapon = _handgunWeapon + ["hgun_Pistol_Signal_F"];
	_pointers = ["Binocular","acc_flashlight","acc_flashlight_pistol","acc_flashlight_smg_01","acc_pointer_IR"];
	_googles = ["NVGoggles","NVGoggles_INDEP","NVGoggles_OPFOR","NVGoggles_tna_F","NVGogglesB_blk_F","NVGogglesB_grn_F","NVGogglesB_gry_F","O_NVGoggles_ghex_F","O_NVGoggles_grn_F","O_NVGoggles_hex_F","O_NVGoggles_urb_F"];
