private _bk = createVehicle [ "O_supplyCrate_F", [14187.6,15993.5,1], [], 0, "CAN_COLLIDE" ];
_bk setVariable ["dnt_remove_me",true];
private _box = getPos _bk;
clearWeaponCargoGlobal _bk;
clearMagazineCargoGlobal _bk;
clearBackpackCargoGlobal _bk;
clearItemCargoGlobal _bk;
        _bk addItemCargoGlobal ["Medikit",1];
        _bk addItemCargoGlobal ["ToolKit",1];
        _bk addItemCargoGlobal ["MineDetector",1];
        _bk addItemCargoGlobal ["NVGoggles_INDEP",5];
        _bk addItemCargoGlobal ["FirstAidKit",20];
        _bk addItemCargoGlobal ["SmokeShellGreen",2];
        _bk addItemCargoGlobal ["SmokeShellOrange",2];
        _bk addItemCargoGlobal ["SmokeShellBlue",2];
        _bk addItemCargoGlobal ["O_IR_Grenade",2];
        _bk addItemCargoGlobal ["ItemGPS",2];
        _bk addBackpackCargoGlobal ["B_AssaultPack_dgtl",2];
        _bk addItemCargoGlobal ["H_HelmetIA",1];
        _bk addItemCargoGlobal ["V_PlateCarrierIA1_dgtl",1];
        _bk addBackpackCargoGlobal ["B_kitbag_rgr",2];
        _bk addItemCargoGlobal ["arifle_Katiba_F",2];
        _bk addItemCargoGlobal ["arifle_AK12_F",2];
        _bk addItemCargoGlobal ["arifle_AKM_F",2];
        _bk addItemCargoGlobal ["arifle_AKS_F",2];
        _bk addItemCargoGlobal ["arifle_AK12U_F",2];
        _bk addItemCargoGlobal ["launch_RPG7_F",2];
        _bk addItemCargoGlobal ["RPG7_F",5];
        _bk addItemCargoGlobal ["RPG32_F",5];
        _bk addItemCargoGlobal ["MRAWS_HEAT_F",10];
        _bk addItemCargoGlobal ["Titan_AA",10];
        _bk addItemCargoGlobal ["SatchelCharge_Remote_Mag",5];
        _bk addItemCargoGlobal ["DemoCharge_Remote_Mag",5];
        _bk addItemCargoGlobal ["SLAMDirectionalMine_Wire_Mag",10];
        _bk addItemCargoGlobal ["ATMine_Range_Mag",4];
        _bk addItemCargoGlobal ["SmokeShell",30];
        _bk addItemCargoGlobal ["HandGrenade",5];
        _bk addItemCargoGlobal ["MiniGrenade",5];
        _bk addItemCargoGlobal ["1Rnd_Smoke_Grenade_shell",10];
        _bk addItemCargoGlobal ["1Rnd_SmokeRed_Grenade_shell",10];
        _bk addItemCargoGlobal ["UGL_FlareWhite_F",10];
        _bk addItemCargoGlobal ["1Rnd_HE_Grenade_shell",20];
        _bk addItemCargoGlobal ["UGL_FlareCIR_F",10];
        _bk addItemCargoGlobal ["30Rnd_65x39_caseless_green",20];
        _bk addItemCargoGlobal ["30Rnd_762x39_Mag_F",20];
        _bk addItemCargoGlobal ["30Rnd_545x39_Mag_F",30];
        _bk addItemCargoGlobal ["30Rnd_556x45_Stanag",30];
        _bk addItemCargoGlobal ["30Rnd_580x42_Mag_F",20];
        _bk addItemCargoGlobal ["30Rnd_65x39_caseless_black_mag",20];
        _bk addItemCargoGlobal ["30Rnd_65x39_caseless_msbs_mag",20];
        _bk addItemCargoGlobal ["20Rnd_650x39_Cased_Mag_F",20],;
        _bk addItemCargoGlobal ["20Rnd_762x51_Mag",20];
        _bk addItemCargoGlobal ["10Rnd_762x54_Mag",20];
        _bk addItemCargoGlobal ["150Rnd_556x45_Drum_Mag_F",5];
        _bk addItemCargoGlobal ["150Rnd_762x54_Box",5];
        _bk addItemCargoGlobal ["200Rnd_65x39_cased_Box",5];
        _bk addItemCargoGlobal ["130Rnd_338_Mag",5],;
        _bk addItemCargoGlobal ["150Rnd_93x64_Mag",5];
        _bk addItemCargoGlobal ["200Rnd_556x45_Box_F",5];
        _bk addItemCargoGlobal ["75rnd_762x39_AK12_Mag_F",5];
        _bk addItemCargoGlobal ["100Rnd_580x42_Mag_F",5];
        _bk addItemCargoGlobal ["100Rnd_65x39_caseless_black_mag",5];
        _bk addItemCargoGlobal ["10Rnd_50BW_Mag_F",10];
        _bk addItemCargoGlobal ["6Rnd_12Gauge_Pellets",10];
        _bk addItemCargoGlobal ["6Rnd_12Gauge_Slug",10];
        _bk addItemCargoGlobal ["Weapon_launch_MRAWS_green_F",1]; 